# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pypss/protos/trace.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "pypss/protos/trace.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18pypss/protos/trace.proto\x12\x05pypss"\xa5\x02\n\x0cTraceMessage\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0e\n\x06lineno\x18\x04 \x01(\x05\x12\x0e\n\x06module\x18\x05 \x01(\t\x12\x10\n\x08\x64uration\x18\x06 \x01(\x01\x12\x10\n\x08\x63pu_time\x18\x07 \x01(\x01\x12\x11\n\twait_time\x18\x08 \x01(\x01\x12\x0e\n\x06memory\x18\t \x01(\x03\x12\x13\n\x0bmemory_diff\x18\n \x01(\x03\x12\r\n\x05\x65rror\x18\x0b \x01(\x08\x12\x16\n\x0e\x65xception_type\x18\x0c \x01(\t\x12\x19\n\x11\x65xception_message\x18\r \x01(\t\x12\x12\n\nbranch_tag\x18\x0e \x01(\t\x12\x11\n\ttimestamp\x18\x0f \x01(\x01"1\n\rTraceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2J\n\x0cTraceService\x12:\n\x0bSubmitTrace\x12\x13.pypss.TraceMessage\x1a\x14.pypss.TraceResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pypss.protos.trace_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_TRACEMESSAGE"]._serialized_start = 36
    _globals["_TRACEMESSAGE"]._serialized_end = 329
    _globals["_TRACERESPONSE"]._serialized_start = 331
    _globals["_TRACERESPONSE"]._serialized_end = 380
    _globals["_TRACESERVICE"]._serialized_start = 382
    _globals["_TRACESERVICE"]._serialized_end = 456
# @@protoc_insertion_point(module_scope)
